# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b9a4ed9d4352628f42b49ca3bf4ff4a2520b3741bdde3edbe6c8882c2d67be30ebcd2d15a6efa1a7a870e4d28f9efcf227c8faf4ed04c2525d11fc4203a0b531

test:
  secret_key_base: 97554d8d966d7ba272b0c4bef0cf15674f130fddc6252fe89173be4bd8ce81ddad4313ebe313377a1a70adb8f6ab51a9d027a71be1de09d29ea958e05324a3b3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
